name: Playwright Regression

on:
  workflow_dispatch:

jobs:

  # =====================================================
  # PLAYWRIGHT SHARDS
  # =====================================================

  test:

    name: Test Shard ${{ matrix.shard }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - shard: 1/4
            shard_name: 1-of-4
          - shard: 2/4
            shard_name: 2-of-4
          - shard: 3/4
            shard_name: 3-of-4
          - shard: 4/4
            shard_name: 4-of-4

    env:
      CI: true
      BASE_URL: https://hq.nyovate.dev

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: TypeScript Check
        run: npx tsc --noEmit

      - name: Run Playwright
        run: |
          npx playwright test \
            --shard=${{ matrix.shard }}

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: allure-results-${{ matrix.shard_name }}
          path: reports/allure-results
          if-no-files-found: warn

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report-${{ matrix.shard_name }}
          path: reports/playwright-report
          if-no-files-found: warn


  # =====================================================
  # MERGE ALLURE RESULTS
  # =====================================================

  allure:

    name: Generate Allure Report

    if: always()

    needs:
      - test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Download Allure Results
        uses: actions/download-artifact@v5
        with:
          pattern: allure-results-*
          path: merged-allure-results
          merge-multiple: true

      - name: Generate Allure Report
        run: |
          allure generate \
            merged-allure-results \
            --clean \
            -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v5
        with:
          name: final-allure-report
          path: allure-report
